src/main/FUCManager/CurricularUnitFormManager/Controllers/IndividualController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using CurricularUnitFormManager.Models.Individual;
using CurricularUnitFormManager.Models.Repository;
using System.IO;

namespace CurricularUnitFormManager.Controllers
{
    public class IndividualController : Controller
    {
        readonly static IndividualRepository _userRepository = IndividualRepository.Instance;
        
       
        public ActionResult Index()
        {
            List<IndividualRepoModel> users = new List<IndividualRepoModel>();
            foreach (Individual user in _userRepository.getUserList())
                users.Add(new IndividualRepoModel(user));
            return View(users);
        }

        [Authorize]
        public ActionResult ViewUser(String username)
        {
            Individual user = (Individual)_userRepository.GetUser(username, true);
            IndividualViewModel ind = new IndividualViewModel();
            ind.User = user;

            return View(ind);
        }


        [Authorize]
        public ActionResult EditUser(String username)
        {
            Individual user = (Individual)_userRepository.GetUser(username, true);
            IndividualViewModel ind = new IndividualViewModel();
            ind.User =user ;

            return View(ind);
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditUser(IndividualViewModel indiv)
        {
            if (indiv.file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(indiv.file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/user"), fileName);
                indiv.file.SaveAs(path);
                Individual user = (Individual)_userRepository.GetUser(indiv.User.UserName, true);
                user.PhotoName = fileName;
            }

            return this.RedirectToAction("ViewUser", new { username = indiv.User.UserName});
        }

    }
}

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_GenericCurricularUnitForm.cshtml
@using CurricularUnitFormManager.Models.CurricularUnit
@model AbstractCurricularUnitForm

    <div class="content">
        <div class="clearfix">
            Nome: @Model.CourseFile.CUnit.Name<br/>
            Acrónimo: @Model.CourseFile.CUnit.Acronym<br/>
            Enquadramento:  @Model.CourseFile.Type.Degree
			                @Model.CourseFile.Type.Semester
			                @Model.CourseFile.Type.CourseType
             <br/>
            Créditos: @Model.CourseFile.CUnit.ECTS<br/>
            Pré-Requesitos:         
            @foreach (var item in Model.CourseFile.RequiredCourses)
            {
                @item.CUnit.Name;
            }
        </div>
    </div>

<h2>Objectivos</h2>
    <p>
    @Model.CourseFile.Description.Objectives<br/><br/>
    </p>
<h2>Resultados de aprendizagem</h2>
    <p>
    @Model.CourseFile.Description.LearningResults<br/><br/>
    </p>
<h2>Avaliação dos resultados de aprendizagem</h2>
    <p>
    @Model.CourseFile.Description.ResultEvaluation<br/><br/>
    </p>
<h2>Programa resumido</h2>
    <p>
    @Model.CourseFile.Description.CourseProgram<br/><br/>
    </p>

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_GenericEditableCurricularUnitForm.cshtml
@model CurricularUnitFormManager.Models.CurricularUnit.AbstractCurricularUnitForm

<div>
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.CUnit.Acronym)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.CourseFile.CUnit.Acronym)
            @Html.ValidationMessageFor(m => m.CourseFile.CUnit.Acronym)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.CUnit.Name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.CourseFile.CUnit.Name)
            @Html.ValidationMessageFor(m => m.CourseFile.CUnit.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Type.Degree)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.CourseFile.Type.Degree)
            @Html.ValidationMessageFor(m => m.CourseFile.Type.Degree)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Type.Semester)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.CourseFile.Type.Semester)
            @Html.ValidationMessageFor(m => m.CourseFile.Type.Semester)
        </div>
        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.CUnit.ECTS)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.CourseFile.CUnit.ECTS)
            @Html.ValidationMessageFor(m => m.CourseFile.CUnit.ECTS)
        </div>
        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Type.CourseType)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.CourseFile.Type.CourseType)
            @Html.ValidationMessageFor(m => m.CourseFile.Type.CourseType)
            (M - Mandatory, O - Optional)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.RequiredCourses)
        </div>
        <div class="editor-field">
           @* @Html.TextBoxFor(m => m.CourseFile.CUnit.Name)*@
            @*@Html.ValidationMessageFor(m => m.RequiredCourses)*@
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Description.Objectives)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(m => m.CourseFile.Description.Objectives)
            @Html.ValidationMessageFor(m => m.CourseFile.Description.Objectives)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Description.LearningResults)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(m => m.CourseFile.Description.LearningResults)
            @Html.ValidationMessageFor(m => m.CourseFile.Description.LearningResults)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Description.ResultEvaluation)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(m => m.CourseFile.Description.ResultEvaluation)
            @Html.ValidationMessageFor(m => m.CourseFile.Description.ResultEvaluation)
        </div>

        <div class="editor-label">
            @Html.LabelFor(m => m.CourseFile.Description.CourseProgram)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(m => m.CourseFile.Description.CourseProgram)
            @Html.ValidationMessageFor(m => m.CourseFile.Description.CourseProgram)
        </div>
    </fieldset>
</div>

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_GenericList.cshtml
@using CurricularUnitFormManager.Models.CurricularUnit
@model IEnumerable<CUFNameURIModel>

<div class="span4">
    <ul>
        @foreach (CUFNameURIModel cuf in Model)
        {
            <li>
                @if (cuf.GetVersion() != 0){
                    @Html.ActionLink(cuf.GetName(), cuf.GetAction(), new { acr = cuf.GetACR(), id = cuf.GetVersion() });
                }else{
                    @Html.ActionLink(cuf.GetName(), cuf.GetAction(), new { acr = cuf.GetACR()});
                }
            </li>
        }
    </ul>
</div>

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Custom.css")" rel="stylesheet" type="text/css" />
    @*<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css" type="text/css">*@
    @*<script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>*@
   	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" type="text/css" media="all" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/_search.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/_page.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Curricular Unit Manager</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                 @Html.Partial("_Menu")

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
                @Html.Partial("_Search")
            </div>
        </div>
    </div>
</body>
</html>

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_LogOnPartial.cshtml

@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
        <ul class="pills" id="menu">
            <li>@Html.ActionLink("Logoff", "Logout", "Account")</li>
            <li>@Html.ActionLink("Profile", "ViewUser", "Individual", new { username = User.Identity.Name }, null)</li>
            @if (User.IsInRole("Administrator"))
            {<li>@Html.ActionLink("User Administration", "Index", "Individual")</li>}
        </ul>
    </text>
}
else {
    <ul class="pills" id="menu">
        <li>@Html.ActionLink("Log On", "Login", "Account")</li>
        <li>@Html.ActionLink("Register", "Register", "Account")</li>
    </ul>
    
}
 

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_Menu.cshtml
<text>
    <ul class="pills" id="menu">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Cuf Manager", "Index", "Cuf")</li>
    @if(Request.IsAuthenticated) {
        <li>@Html.ActionLink("New Proposal", "New", "Proposal")</li>
    }
    </ul>
</text>


 

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_Page.cshtml
@using CurricularUnitFormManager.Models.CurricularUnit
@model CUFsListViewModel
<div id="teste"><h1>@ViewBag.ajax</h1></div>
<span id = "ItemsOrderSpan">
    <label>Order</label>
    @foreach( String o in Model.OrderPage){
        <label>
        [@Html.ActionLink("" + o + "", Model.Method, new { pagenr = Model.PageNumber, itemsnr = Model.ItemsNumber, order = o })]
        </label>
    }
</span>

<span id = "ItemsNbrSpan">
    <label>Page</label>
    @foreach( int p in Model.ItemsPerPage){
        <label>
        [@Html.ActionLink("" + p + "", Model.Method, new { pagenr = Model.PageNumber, itemsnr = p, order = Model.Order })]
        </label>
    }
</span>

<div id = "CufListDiv">
    @{Html.RenderPartial("_GenericList", Model.CUFList);}
</div>

<div id = "PageNavigationDiv" >
    @if (Model.PageNumber > 0)
    {
        <label>
        [@Html.ActionLink("First", Model.Method, new { pagenr = 0, itemsnr = Model.ItemsNumber, order = Model.Order })]
        </label> 
        <label>
        [@Html.ActionLink("Previous", Model.Method, new { pagenr = (Model.PageNumber - 1), itemsnr = Model.ItemsNumber, order = Model.Order })]
        </label>
    }
    @for(int i = 0 ; i < Model.AmountPage; ++i){
        if (i == Model.PageNumber)
        {
            <label>
            [@i]
            </label>
        }
        else 
        { 
            <label>
            [@Html.ActionLink("" + i, Model.Method, new { pagenr = i, itemsnr = Model.ItemsNumber, order = Model.Order })]
            </label> 
        }
    }
    @if (!Model.LastPage)
    {
         <label>
         [@Html.ActionLink("Next", Model.Method, new { pagenr = (Model.PageNumber + 1), itemsnr = Model.ItemsNumber, order = Model.Order })]
         </label>
         <label>
         [@Html.ActionLink("Last", Model.Method, new { pagenr = (Model.AmountPage - 1), itemsnr = Model.ItemsNumber, order = Model.Order })]
         </label>
    }
</div>

src/main/FUCManager/CurricularUnitFormManager/Views/Shared/_search.cshtml
<div id="SearchDiv">
    @using (Html.BeginForm("Search", "Official", FormMethod.Get, new { id = "SearchForm" }))
    {
    <div id="SearchInputDiv">
        
            <label for="tags">Search:</label>
            <input id="tags" type="text" name="SearchValue"/>
            <input id="SearchButton" type="submit" value="Search"/>
    </div>
    }

</div>